version: '3.3'

services:
  db:
    image: mariadb:11
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: passwd
      MYSQL_DATABASE: app

    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql
      - ./conf:/etc/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: passwd
    ports:
      - "8080:80"
    depends_on:
      - db

