version: '2.0'
services:
  registry:
    image: registry:2.7
    volumes:
      - .:/var/lib/registry
    ports:
      - 5000:5000
    restart: always
    networks:
      - registry-ui-net

  registry-ui:
    image: joxit/docker-registry-ui:latest
    restart: always
    ports:
      - 80:80
    environment:
      - REGISTRY_TITLE=My Private Docker Registry
      - NGINX_PROXY_PASS_URL=http://registry:5000
      - SINGLE_REGISTRY=true
    depends_on:
      - registry
    networks:
      - registry-ui-net

networks:
  registry-ui-net:
