version: '3'
services:
  minio:
    image: quay.io/minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./data:/data
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: passwd
    command: server /data --console-address ":9001"
    restart: always

